### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by cesarlpb** [LanLop1/proyecto_final#1]
hago cosas

header responsive a medida con UI/UX state-of-the-art

ez

**Comment by alma8026** [comment]
wow

**Comment by LanLop1** [comment]
hecho

**Comment by cesarlpb** [comment]
eggcelente
*Cesar Patino*
.NET C# Developer · Blockchain Consultant
Techs I have used: C++, C, Python, SQL, MySQL, MariaDB, Linux, NGINX,
Apache, and many more

*Linkedin:* https://www.linkedin.com/in/cesarlpb89/
*UpWork profile: *https://www.upwork.com/freelancers/cesarlpb
If you have received this e-mail by mistake, please delete it. For any
inquiry, please contact me at: ***@***.***
